FROM amazoncorretto:21-alpine-jdk@sha256:8b16834e7fabfc62d4c8faa22de5df97f99627f148058d52718054aaa4ea3674

RUN apk add inotify-tools

WORKDIR /sidecar
RUN chown 1000:1000 /sidecar

COPY --chown=1000 debugwatch.sh .
RUN chmod +x debugwatch.sh

COPY --chown=1000 build/distributions/productcatalog.tar .

USER 1000
ENTRYPOINT ["./debugwatch.sh"]
