POST http://localhost:8081/checkout HTTP/1.1
content-type: application/json

{
    "userID": "user1",
    "userCurrency": "DKK",
    "address": {
        "streetAddress": "Campusvej 55",
        "city": "Odense",
        "state": "fyn",
        "country": "Danmark",
        "zipCode": 5230
    },
    "email": "user@example.com",
    "creditCart": {
        "number": "111-222-333-444",
        "cvv": 321,
        "expirationYear": 2027,
        "expirationMonth": 8
    }
}
